### ISSUE TITLE
Problem 6. Point in Circle wrong example answers

### ISSUE THREAD

**Issue by dtopalov** [TelerikAcademy/JavaScript-Fundamentals#2]
Write an expression that checks if given point P(x, y) is within a circle K(O, 5).

-1  2   false
-1.5    -1.5    false
0.9 -1.93   false

If I understand the task (circle with center at 0, 0 and radius = 5), all of these should be true.

**Comment by KonstantinSimeonov** [comment]
Fixed with commit 17d09c354af984fdb9a4815cd552eeb1e0bcb15a
