### ISSUE TITLE
Small problem with Hyperlinks

### ISSUE THREAD

**Issue by Tuscann** [TelerikAcademy/JavaScript-Fundamentals#21]
https://github.com/TelerikAcademy/JavaScript-Fundamentals/tree/master/Topics/08.%20Functions
Declaring and Calling Functions - Demo
Redirect on Demo link not work - not show demo folder!
demo folder exist but link to her not work properly.

**Comment by cuklev** [comment]
Fixed with 25b7b3999d670337c507eb7706d5bcf688e4d4bf
